apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
  #  namespace: elk-selenium
  labels:
    app: selenium-hub
spec:
  ports:
  - port: 4444
    targetPort: 4444
    name: port0
  selector:
    app: selenium-hub
  type: ClusterIP
  sessionAffinity: None
